# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
News.create([ 

{title: 'Niner Nights', 
date: 'Summer 2014', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/qcb575tusx9el2h.jpg', 
description: 'Come out to visit the AIM booth during Niner Nights on the UNC Charlotte campus! future freshman signed AIM\'s door to "open your door from dreams to reality!"'},

{title: 'General Body Meeting', 
date: 'Summer 2014', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/glmat55f2qq8u1l.png', 
description: 'AIM launched this year with its first general body meeting! Members were introduced to AIM&\'s purpose and goals for this year as well as information about future events and opportunities.'},

{title: 'CF Cycle for Life', 
date: 'October 18, 2014', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/uzinlh0g54u7hpi.png', 
description: 'AIM helped the Cystic Fibrosis FOundation hold the CF Cycle for Life bicycle marathon. Members helped out with the biker\'s celebrations for completing the marathon.'},

{title: 'Homecoming Parade!!!', 
date: 'October 24, 2014', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/qcdr3carqcj5cem.png', 
description: 'AIM marched in the 2014 Homecoming Lights Parade! AIM represented this year\'s theme in style, displaying a truck covered in glowing sticks and balloons.'},

{title: 'Fall Interest Meeting', 
date: 'January 26, 2015', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/dzekaagmcmpvktd.jpg', 
description: 'AIM welcomed new members at our second interest meeting. Guests were welcomed with fun activities and Bo-Berry Biscuits!'},

{title: 'Guest Jeff Brokaw', 
date: 'February 2, 2015', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/3gb2btdvx9034ou.jpg', 
description: 'AIM had the pleasure to host successful entrepreneur Jeff Brokaw! He discussed his new company AppVested and the entrepreneurial workshops he hosts for Google\'s StartUp Grind.'},

{title: 'Investor Competition!', 
date: 'February 23, 2015', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/w7tjjk5z0np362j.jpg', 
description: 'AIM members had five minutes to develop a pitch that would pique the investor\'s interests'},

{title: 'Investing 101: Campbell O\'Bleans', 
date: 'March 9, 2015', 
mediatype: 'Video', 
thumburl: 'https://www.youtube.com/embed/JUKyaxz_1IY', 
description: 'AIM\'s Fundraising Chair Campbell O\'Bleans presented on tips for young investors and how to manage your finances.'},

{title: 'Using LinkedIn: Raymond Ferrell', 
date: 'March 16, 2015', 
mediatype: 'Video', 
thumburl: 'https://www.youtube.com/embed/1i5Uf3SmUQU', 
description: 'Vice President Raymond Ferrell hosted a seminar on building a digital network on a global scale using LinkedIn'},

{title: 'Bark For Life!', 
date: 'March 21, 2015', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/a4tqvgczj7ab6al.jpg', 
description: 'AIM volunteered for Bark for Life, a canine event to raise funds for cancer research!'},

{title: 'UX Testing with Zerrick Bynum', 
date: 'April 13, 2015', 
mediatype: 'Video', 
thumburl: 'https://www.youtube.com/embed/6beKnkPZRxE', 
description: 'President Dreu Dixon and the founder of Happzee.com, Zerrick Bynum hosted a usability testing workshop!'},

{title: 'New Student Org of the Year!!', 
date: 'April 20, 2015', 
mediatype: 'Image', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/houuc4y6h4u5foh.jpg', 
description: 'AIM was chosen out of 51 new student organizations as the Outstanding New Student Organization of 2015!'}])

Member.create([
{first_name: 'Raymond', 
last_name: 'Ferrell', 
major: 'Computer Science', 
graduation_date: 'Dec 2016', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/cbh6u36l6mmg7md.jpg', 
linkedinurl: 'http://www.linkedin.com/pub/raymond-ferrell/78/263/a61', 
email: 'aimunccpresident@gmail.com', 
is_executive: true, 
executive_position: 'President'},

{first_name: 'Campbell', 
last_name: 'O\'Bleans', 
major: 'Pre-Law', 
graduation_date: '', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/s2rui0rsh6sazk9.jpg', 
linkedinurl: '', 
email: 'aimunccvicepresident@gmail.com', 
is_executive: true, 
executive_position: 'Vice President'},

{first_name: 'Mickey', 
last_name: 'Fowler', 
major: 'Accounting', 
graduation_date: '', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/k9q5n5rdyc34k83.png', 
linkedinurl: 'https://www.linkedin.com/in/mickeyrfowler', 
email: 'aimuncctreasurer@gmail.com', 
is_executive: true, 
executive_position: 'Treasurer'},

{first_name: 'Asya', 
last_name: 'Etheridge', 
major: '', 
graduation_date: '', 
thumburl: '', 
linkedinurl: '', 
email: 'aimunccsecretary@gmail.com', 
is_executive: true, 
executive_position: 'Secretary'},

{first_name: 'Larry', 
last_name: 'Ogunjobi', 
major: 'Computer Science', 
graduation_date: '', 
thumburl: 'https://media.licdn.com/media/AAEAAQAAAAAAAAMWAAAAJDU5Y2Q3ZTAzLTIwMTAtNDcxMC05MmVjLTEzODhjZTk0YjI5MQ.jpg', 
linkedinurl: 'https://www.linkedin.com/pub/larry-ogunjobi/b4/906/779', 
email: 'aimunccprograms@gmail.com', 
is_executive: true, 
executive_position: 'Director of Programs'},

{first_name: 'Adina', 
last_name: 'Houston', 
major: 'International Business', 
graduation_date: '', 
thumburl: 'https://media.licdn.com/media/AAEAAQAAAAAAAASZAAAAJGYwM2U0OWY4LTM4NGEtNGZmNi1iYTY3LWUwZWEyNTkwZDg1NA.jpg', 
linkedinurl: 'https://www.linkedin.com/pub/adina-houston/a4/422/836', 
email: 'aimunccpartnership@gmail.com', 
is_executive: true, 
executive_position: 'Director of Strategic Partnerships'},

{first_name: 'Daniel', 
last_name: 'Brown', 
major: '', 
graduation_date: '', 
thumburl: '', 
linkedinurl: '', 
email: 'aimunccpr@gmail.com', 
is_executive: true, 
executive_position: 'Director of Public Relations'},

{first_name: 'Amanda', 
last_name: 'Kassay', 
major: 'Systems Engineering', 
graduation_date: '', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/06od11o7a0b6he5.jpg', 
linkedinurl: 'https://www.linkedin.com/pub/amanda-kassay/95/901/264', 
email: 'aimuncccommunity@gmail.com', 
is_executive: true, 
executive_position: 'Director of Community Service'},

{first_name: 'London', 
last_name: 'Hawkins', 
major: '', 
graduation_date: '', 
thumburl: 'https://d1q9wbuypc40mm.cloudfront.net/vos7s1b4h9b21y7.jpg', 
linkedinurl: '', 
email: 'aimuncchistorian@gmail.com', 
is_executive: true, 
executive_position: 'Historian'},

{first_name: 'TK', 
last_name: 'Jordan', 
major: '', 
graduation_date: '', 
thumburl: '', 
linkedinurl: '', 
email: 'aimunccdigital@gmail.com', 
is_executive: true, 
executive_position: 'Digital Administrator'}])

User.create( 
user_name: 'ADMIN', 
first_name: 'AIM', 
last_name: 'ADMIN', 
email: ENV['ADMIN_EMAIL_DEV'], 
password: ENV['ADMIN_PASSWORD_DEV'], 
role: 'admin' )
